logging:
  level:
    io:
      mend:
        seed: INFO
spring:
  application:
    name: seed4jSampleApplication
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      poolName: Hikari
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/seed4jSampleApplication
    username: seed4jSampleApplication
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  jackson:
    default-property-inclusion: non_absent
management:
  endpoint:
    health:
      access: read-only
      probes:
        enabled: true
      show-details: always
  endpoints:
    access:
      default: none
    jmx:
      exposure:
        exclude: '*'
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
server:
  port: 8080
