logging:
  level:
    io:
      mend:
        seed: INFO
spring:
  application:
    name: seed4jSampleApplication
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      poolName: Hikari
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/seed4jSampleApplication
    username: seed4jSampleApplication
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  jackson:
    default-property-inclusion: non_absent
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:9080/realms/seed4j
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app
            scope: openid,profile,email
management:
  endpoint:
    health:
      access: read-only
      probes:
        enabled: true
      show-details: always
  endpoints:
    access:
      default: none
    jmx:
      exposure:
        exclude: '*'
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
  info:
    env:
      enabled: true
    # Git Information
    git:
      enabled: true
      mode: full
server:
  port: 8080
application:
  security:
    oauth2:
      audience: account,api://default
springdoc:
  enable-native-support: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
    oauth:
      client-id: web_app
      realm: seed4j
  oauth2:
    authorization-url: http://localhost:9080/realms/seed4j/protocol/openid-connect/auth
